common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'common'

urlpatterns = [
    #path('', views.main, name='main'),
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('find_id/', views.find_id, name='find_id'),
    path('find_pw/', views.find_pw, name='find_pw'),
    path('find_pw/reset_pw/<int:pk>', views.reset_pw, name='reset_pw'),
    path('find_pw/verify/<int:pk>', views.verify, name='verify'),
    path('lecture/searching/', views.searched_lecture, name='searched_lecture'),
    path('message/', views.customer_message, name='customer_message'),
    path('subscribe/', views.subscribe, name='subscribe'),
]

lecture/urls.py
from django.urls import path
from . import views

app_name = 'lecture'

urlpatterns = [
    path('', views.LectureList.as_view(), name='index'),
    path('<int:pk>/', views.LectureDetail.as_view(), name='detail'),
    path('category/<str:slug>/', views.category_page),
    path('create/', views.lecture_create, name='lecture_create'),
    path('<int:lecture_id>/update/', views.lecture_update, name='lecture_update'),
    path('<int:lecture_id>/delete/', views.lecture_delete, name='lecture_delete'),
]

management/urls.py
from django.contrib import admin
from django.urls import path, include
from common.views import HomeView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('lecture/', include('lecture.urls')),
    path('common/', include('common.urls')),
    path('my_page/', include('my_page.urls')),
    path('qna/', include('qna.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qna/urls.py
from django.urls import path
from . import views

app_name = 'qna'

urlpatterns = [
    path('', views.index, name='index'),
    # 127.0.0.1:8000/qna 가 디폴트
    path('<int:question_id>/', views.detail, name='detail'),
    # 127.0.0.1:8000/qna/ + int값이 들어옴 -> question_id
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    # 127.0.0.1:8000/qna/answer/creat/number$$$
    path('question/create/', views.question_create, name='question_create'),
    # 127.0.0.1:8000/qna/question/create/
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    path('comment/create/question/<int:question_id>/', views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', views.comment_delete_answer, name='comment_delete_answer'),
    path('vote/question/<int:question_id>/', views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', views.vote_answer, name='vote_answer'),
]

common/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    self_prove = models.CharField(max_length=50)
    self_prove_answer = models.CharField(max_length=50)

    def __str__(self):
        return self.username


class CustomerMessage(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    subject = models.CharField(max_length=50)
    message = models.CharField(max_length=500)

    def __str__(self):
        return self.subject


class NewsAgreedCustomer(models.Model):
    email = models.EmailField()

    def __str__(self):
        return "Subscribed Customer"

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from django.contrib.auth.models import Group


class UserForm(UserCreationForm):
    last_name = forms.CharField(label="성")
    first_name = forms.CharField(label="이름")
    email = forms.EmailField(label="이메일")
    self_prove = forms.CharField(label='본인인증 질문')
    self_prove_answer = forms.CharField(label='본인인증 질문 정답')

    class Meta:
        model = CustomUser
        fields = (
            "username",
            "last_name",
            "first_name",
            "password1",
            "password2",
            "email",
            "self_prove",
            "self_prove_answer"
        )

    def save(self):
        user = super(UserForm, self).save(commit=False)
        user.save()
        try:
            student = Group.objects.get(name='student')
            student.user_set.add(user)
        except Group.DoesNotExist:
            student = Group.objects.create(name='student')
            student.user_set.add(user)
        return

    # 보통 meta 클래스는 field로 정의 할 수 없는 것들을 정의하기 위해 사용한다는 것인데
    # 순서(order)나 단수 복수형 추가(안하면 뒤에 s만 붙음)
    # wikidocs에서 왜 이렇게 쓴느지는 잘 모르겠음


class StaffForm(UserCreationForm):
    last_name = forms.CharField(label="성")
    first_name = forms.CharField(label="이름")
    email = forms.EmailField(label="이메일")
    teacher_code = forms.CharField(label='강사코드')
    self_prove = forms.CharField(label='본인인증 질문')
    self_prove_answer = forms.CharField(label='본인인증 질문 정답')

    class Meta:
        model = CustomUser
        fields = (
            "username",
            "last_name",
            "first_name",
            "password1",
            "password2",
            "email",
            "self_prove",
            "self_prove_answer"
        )

    def save(self):
        user = super(StaffForm, self).save(commit=False)
        user.is_staff = True
        user.save()
        try:
            teacher = Group.objects.get(name='teacher')
            teacher.user_set.add(user)
        except Group.DoesNotExist:
            teacher = Group.objects.create(name='teacher')
            teacher.user_set.add(user)
        return

common/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import TemplateView
from typing import Any, Dict
from .forms import UserForm, StaffForm
from .models import CustomUser as User
from .models import CustomerMessage, NewsAgreedCustomer
from django.contrib.auth.forms import PasswordChangeForm
from django.urls import reverse_lazy
from lecture.models import Lecture, Category
from functools import reduce
from operator import and_
import ast
from django.http import HttpResponse, HttpResponseRedirect


# Create your views here.


class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        return context


def signup(request):
    if request.method == 'POST':  # request 들어온 것이 post방식이면
        if request.POST['teacher_code'] in ['A0001', 'A0002']:
            form = StaffForm(request.POST)
        else:
            form = UserForm(request.POST)  # form에 UserForm post version으로 저장한다
        if form.is_valid():  # form이 valid하면
            form.save()
            return redirect('../login')
    else:
        form = UserForm()  # 계정 생성 화면 리턴
    return render(request, './common/signup.html', {'form': form})


def find_id(request):
    if request.method == 'POST':
        try:
            user = User.objects.get(
                email=request.POST['email'],
                first_name=request.POST['first_name'],
                last_name=request.POST['last_name']
            )
            context = {'username': user.username}
            return render(request, './common/find_id.html', context)
        except ObjectDoesNotExist:
            context = {'username': "None"}
            return render(request, './common/find_id.html', context)

    else:
        return render(request, './common/find_id.html')


def find_pw(request):
    if request.method == "POST":
        try:
            user = User.objects.get(
                username=request.POST['username'],
                email=request.POST['email'],
                first_name=request.POST['first_name'],
                last_name=request.POST['last_name']
            )
            return redirect('common:verify', pk=user.pk)
        except ObjectDoesNotExist:
            context = {'error_message': '입력하신 정보를 확인해주세요'}
            return render(request, './common/verify.html', context)
    else:
        return render(request, './common/find_pw.html')


def verify(request, pk):
    if request.method == 'POST':
        return redirect('common:reset_pw', pk)
    else:
        user = User.objects.get(pk=pk)
        question = user.self_prove
        answer = user.self_prove_answer
        context = {
            'question': question,
            'answer': answer,
            'pk': pk
        }
        return render(request, './common/verify.html', context)


def reset_pw(request, pk):
    if request.method == 'POST':
        user = User.objects.get(pk=pk)
        password1 = request.POST.get('password1', '')
        password2 = request.POST.get('password2', '')

        if password1 == password2:
            user.set_password(password1)
            user.save()
            return redirect('common:login')
        else:
            return render(request, '/', context)

    else:
        user = User.objects.get(pk=pk)
        username = user.username
        email = user.email
        context = {
            'username': username,
            'email': email,
            'pk': pk
        }
        return render(request, './common/reset_pw.html', context)


def searched_lecture(request):
    if request.method == 'POST':
        categories = Category.objects.all()
        term_list = request.POST['term_list']
        sub_term = request.POST['sub_term']
        if len(term_list) < 1:
            term_list = []
        else:
            term_list = ast.literal_eval(term_list)
        term_list.append(sub_term)
        term_list = list(set(term_list))  # 중복 단어 삭제
        lecture_list = reduce(and_, (Lecture.objects.filter(class_name__icontains=term)
                                     | Lecture.objects.filter(subject__icontains=term)
                                     | Lecture.objects.filter(level__icontains=term)
                                     | Lecture.objects.filter(content__icontains=term) for term in term_list))
        context = {'lecture_list': lecture_list, 'term_list': term_list, 'categories': categories}
        return render(request, './common/searched_lecture.html', context)
    else:
        categories = Category.objects.all()
        term_list = [request.GET['searching']]
        print(term_list, type(term_list))
        lecture_list = reduce(and_, (Lecture.objects.filter(class_name__icontains=term)
                                     | Lecture.objects.filter(subject__icontains=term)
                                     | Lecture.objects.filter(level__icontains=term)
                                     | Lecture.objects.filter(content__icontains=term) for term in term_list))
        context = {'lecture_list': lecture_list, 'term_list': term_list, 'categories': categories}
        return render(request, './common/searched_lecture.html', context)


def customer_message(request):
    message = CustomerMessage(
        name=request.POST['name'],
        email=request.POST['email'],
        subject=request.POST['subject'],
        message=request.POST['message']
    )
    message.save()
    return redirect('/#contact')


def subscribe(request):
    if request.method == "POST":
        subscribe_email = NewsAgreedCustomer(
            email=request.POST['email']
        )
        subscribe_email.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

common/templates/common/find_id.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <title>Find ID</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'images/icons/favicon.ico' %}">

    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">

    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">

    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">

    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">

    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">

    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">

    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">

    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">

    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/login_util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login_main.css' %}">

    <!--===============================================================================================-->

</head>
<body>
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            {% if username %}
            {% if username == "None" %}
            <p style="font-size:18px;color:white">입력하신 정보에 맞는 계정은 없습니다.<br> 다시 확인해주세요.</p><br>
            <div class="container-login100-form-btn">
                <button type="button" onclick="location.href='{% url 'common:find_id' %}'" class="login100-form-btn mr-3">
                    뒤로
                </button>
            </div>
            {% else %}
            <p style="font-size:20px;color:white">
                귀하의 계정은
            <b>{{username}}</b>
                입니다.<br>
            </p>
            <br>
            <div class="container-login100-form-btn">
                <button type="button" onclick="location.href='{% url 'common:find_pw' %}'" class="login100-form-btn mr-3">
                    <b>비밀번호 리셋</b>
                </button> &nbsp;&nbsp;
                <button type="button" onclick="location.href='/'" class="login100-form-btn mr-3">
                    <b>메인</b>
                </button>
            </div>
            {% endif %}
            {% else %}
            <form class="login100-form validate-form" method="post" action="{% url 'common:find_id' %}">
                {% csrf_token %}
                {% include "form_errors.html" %}
                <span class="login100-form-logo">
						<i class="zmdi zmdi-landscape" onclick="location.href='/'"></i>
                </span>
                <span class="login100-form-title p-b-34 p-t-27">
						Find ID
                </span>
                <div class="wrap-input100 validate-input" data-validate = "Enter Email">
                    <input class="input100" type="email" name="email" placeholder="Email" id="email"
                           value="{{ form.email.value|default_if_none:'' }}">
                    <span class="focus-input100" data-placeholder="&#xf207;"></span>
                </div>
                <div class="wrap-input100 validate-input" data-validate = "Enter Last Name">
                    <input class="input100" type="text" name="last_name" placeholder="Last Name" id="last_name"
                           value="{{ form.last_name.value|default_if_none:'' }}">
                    <span class="focus-input100" data-placeholder="&#xf207;"></span>
                </div>
                <div class="wrap-input100 validate-input" data-validate = "Enter First Name">
                    <input class="input100" type="text" name="first_name" placeholder="First Name" id="first_name"
                           value="{{ form.first_name.value|default_if_none:'' }}">
                    <span class="focus-input100" data-placeholder="&#xf207;"></span>
                </div>
                <div class="container-login100-form-btn">
                    <button type="submit" class="login100-form-btn mr-3">
                        Find
                    </button>
                </div>
            </form>
            {% endif %}
        </div>
    </div>
</div>


<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>

<!--===============================================================================================-->
<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>

<!--===============================================================================================-->
<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<!--===============================================================================================-->
<script src="{% static 'vendor/select2/select2.min.js' %}"></script>

<!--===============================================================================================-->
<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>

<!--===============================================================================================-->
<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>

<!--===============================================================================================-->
<script src="{% static 'js/login_main.js' %}"></script>

</body>
</html>

common/templates/common/login.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'images/icons/favicon.ico' %}">

	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">

	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">

	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">

	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">

	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">

	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">

	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">

	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">

	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/login_util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login_main.css' %}">

	<!--===============================================================================================-->
</head>
<body>
<div class="limiter">
	<div class="container-login100">
		<div class="wrap-login100">
			<form class="login100-form validate-form" method="post" action="{% url 'common:login' %}">
				{% csrf_token %}
				{% include "form_errors.html" %}
				<span class="login100-form-logo">
						<i class="zmdi zmdi-landscape" onclick="location.href='/'"></i>
				</span>
				<span class="login100-form-title p-b-34 p-t-27">
						Log in
				</span>
				<div class="wrap-input100 validate-input" data-validate = "Enter username">
					<input class="input100" type="text" name="username" placeholder="Username" id="username"
						   value="{{ form.username.value|default_if_none:'' }}">
					<span class="focus-input100" data-placeholder="&#xf207;"></span>
				</div>
				<div class="wrap-input100 validate-input" data-validate="Enter password">
					<input class="input100" type="password" name="password" placeholder="Password" id="password"
						   value="{{ form.password.value|default_if_none:'' }}">
					<span class="focus-input100" data-placeholder="&#xf191;"></span>
				</div>
				<div class="container-login100-form-btn">
					<button type="submit" class="login100-form-btn mr-3">
						Login
					</button>&nbsp;&nbsp;
					<button type="button" id="goBack" class="login100-form-btn" onclick="location.href='{% url 'common:signup' %}'">
						Sign Up
					</button>
				</div>
				<div class="text-center p-t-90">
					<a class="txt1" href='{% url "common:find_id" %}'>
						Forgot ID?
					</a>
					<br>
					<a class="txt1" href='{% url "common:find_pw" %}'>
						Forgot PW?
					</a>
				</div>
			</form>
		</div>
	</div>
</div>


<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>

<!--===============================================================================================-->
<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>

<!--===============================================================================================-->
<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<!--===============================================================================================-->
<script src="{% static 'vendor/select2/select2.min.js' %}"></script>

<!--===============================================================================================-->
<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>

<!--===============================================================================================-->
<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>

<!--===============================================================================================-->
<script src="{% static 'js/login_main.js' %}"></script>

</body>
</html>

common/templates/common/searched_lecture.html
{% extends 'base_lecture_list.html' %}
{% block main_area %}

<script>
function search(){
    let searchValue = document.getElementById('searching').value.trim();
    if(searchValue.length > 1){
        location.href="/lecture/search" + searchValue + "/";
    }
    else{
        alert('검색어(' + searchValue + ')가 너무 짧습니다.');
    }
};
</script>
<div class="row">
    <div class="col-md-3 col-lg-2" id="sidebar-wrapper">
        <div class="shop-widget" id="categories-card">
            <aside class="widget widget-categories">
                <ul class="list-group">
                    <li class="list-group-item bg-light">
                        <h2 class="sidebar-title text-center">
                        Category
                        </h2>
                    </li>
                    <li class="list-group-item bg-light">
                        <i class="fa fa-angle-double-right"></i>
                        <a href="/lecture/">
                            전체
                        </a>
                    </li>
                    {% for c in categories %}
                    <li class="list-group-item bg-light">
                        <i class="fa fa-angle-double-right"></i>
                        <a href="{{ c.get_absolute_url }}">
                            {{ c }}
                        </a>
                    </li>
                    {% endfor %}
                    <li class="list-group-item bg-light">
                        <i class="fa fa-angle-double-right"></i>
                        <a href="/lecture/category/no_category">미분류</a>
                    </li>
                    <li class="list-group-item bg-light">
                        <form id="rescan" name="rescan" action="{% url 'common:searched_lecture' %}" method="post">
                            {% csrf_token %}
                            {% include "form_errors.html" %}
                            세부 검색<br>
                            <input type="hidden" id="term_list" name="term_list" value="{{term_list}}">
                            <input type="text" id="sub_term" name="sub_term" style="width:100%; max-width:180px"><br>
                            <div class="widget-buttom">
                                <input type="submit" value="검색">
                                <a href="/lecture">검색어 리셋</a>
                            </div>
                        </form>
                    </li>
                </ul>
            </aside>
        </div>
    </div>
    <div class="album py-5 col-md-9 col-lg-10" id="main_area">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for l in lecture_list %}
            <a href="{{ l.get_absolute_url }}">
                <div class="col mb-5">
                    <div class="card shadow-sm">
                        {% if l.lecture_image %}
                        <img class="card-img-top" src="{{ l.lecture_image.url }}" alt="Card image cap" width="100px" height="250px">
                        {% endif %}
                        <div class="card-body">
                            <p class="card-text"> {{ l.class_name }}</p>
                            <div class="d-flex justify-content-between align-items-right">
                                <small class="text-muted">{{ l.student }}</small>
                                <small class="text-muted float-right">{{ l.level }} </small>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            {% endfor %}
        </div>
    </div>
</div>
{% if user.is_staff %}
<a href="{% url 'lecture:lecture_create' %}" class="btn btn-primary float-right">강의 등록</a>
{% endif %}
<div class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <a class="listbutton" href="?page=1"><button type="button" class="btn btn-dark">이전</button></a>&nbsp&nbsp&nbsp
    {%endif%}
    {% for page_number in page_obj.paginator.page_range %}
    {% if page_number >= page_obj.number|add:-5 and page_number <= page_obj.number|add:5 %}
    {% if page_number == page_obj.number %}
    <div class="page-item active" aria-current="page">
        <a class="page-link btn btn-white" href="?page={{ page_number }}">{{ page_number }}</a>
    </div>
    {% else %}
    <div class="page-item">
        <a class="page-link btn btn-white" href="?page={{ page_number }}">{{ page_number }}</a>
    </div>
    {% endif %}
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <a class="listbutton" href="?page={{page_obj.paginator.num_pages}}"><button type="button" class="btn btn-dark">다음</button></a>
    {%endif%}
</div>
{% endblock %}