lecture/urls.py
from django.urls import path
from . import views

app_name = 'lecture'

urlpatterns = [
    path('', views.LectureList.as_view(), name='index'),
    path('<int:pk>/', views.LectureDetail.as_view(), name='detail'),
    path('category/<str:slug>/', views.category_page),
    path('create/', views.lecture_create, name='lecture_create'),
    path('<int:lecture_id>/update/', views.lecture_update, name='lecture_update'),
    path('<int:lecture_id>/delete/', views.lecture_delete, name='lecture_delete'),
]

management/urls.py
from django.contrib import admin
from django.urls import path, include
from common.views import HomeView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('lecture/', include('lecture.urls')),
    path('common/', include('common.urls')),
    path('my_page/', include('my_page.urls')),
    path('qna/', include('qna.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_page/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'my_page'
urlpatterns = [
    path('', views.my_page, name='my_page'),
    path('update/', views.update, name='update'),
    path('my_lecture/', views.my_lecture, name='my_lecture'),
    path('delete/', views.delete, name='delete'),
    path('join_lecture/<int:id>', views.join_lecture, name='join_lecture'),
    path('cancel_lecture/<int:id>', views.cancel_lecture, name='cancel_lecture'),
    path('lecture_concern/<int:id>', views.lecture_concern, name='lecture_concern'),
    path('concerned_lecture/', views.concerned_lecture, name='concerned_lecture'),
    path('my_qna/', views.my_qna, name='my_qna'),
    # path('answer_url/<int:answer_id>', views.answer_url, name='answer_id'),
]

qna/urls.py
from django.urls import path
from . import views

app_name = 'qna'

urlpatterns = [
    path('', views.index, name='index'),
    # 127.0.0.1:8000/qna 가 디폴트
    path('<int:question_id>/', views.detail, name='detail'),
    # 127.0.0.1:8000/qna/ + int값이 들어옴 -> question_id
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    # 127.0.0.1:8000/qna/answer/creat/number$$$
    path('question/create/', views.question_create, name='question_create'),
    # 127.0.0.1:8000/qna/question/create/
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    path('comment/create/question/<int:question_id>/', views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', views.comment_delete_answer, name='comment_delete_answer'),
    path('vote/question/<int:question_id>/', views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', views.vote_answer, name='vote_answer'),
]

my_page/models.py
import datetime

from django.db import models
from django.conf import settings
# Create your models here.

# class Profile(models.Model):
#    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

my_page/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import check_password

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['email']

class PasswordCheckForm(forms.Form):
    password = forms.CharField(label='비밀번호', widget=forms.PasswordInput(
        attrs={'class': 'form-control',})
    )

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        user_password = self.user.password

        if password:
            if check_password(password, user_password) == False:
                self.add_error('password', '비밀번호가 일치하지 않습니다.')

my_page/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView, ListView, View
from django.http import HttpResponseForbidden, HttpResponseRedirect
from common.models import CustomUser as User
from lecture.models import Lecture
from .forms import CustomUserChangeForm, PasswordCheckForm
from qna.models import Question, Answer, Comment
from qna.views import detail



# # Create your views here.

#마이페이지
def my_page(request):
    if request.user.is_authenticated:
        user = request.user
        first_name = request.user.first_name
        last_name = request.user.last_name
        full_name = first_name+last_name
        lectures = Lecture.objects.filter(member=user)
        concerned_lectures = Lecture.objects.filter(lecture_concern=user)
        my_questions = Question.objects.filter(author_id=user)
        my_answers = Answer.objects.filter(author_id=user)
        my_comments = Comment.objects.filter(author_id=user)

        context = {
            'username': user,
            'first_name': first_name,
            'last_name': last_name,
            'full_name': full_name,
            'lectures': lectures,
            'concerned_lectures': concerned_lectures,
            'my_questions': my_questions,
            'my_answers': my_answers,
            'my_comments': my_comments,


        }

        return render(request, 'my_page/my_page.html', context)
    else:
        return redirect('/common/login')


#정보수정페이지
@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = CustomUserChangeForm(instance=request.user)
        context = {'form': form}
    return render(request, 'my_page/update.html', context)




#나의수강정보
def my_lecture(request):
    user = request.user
    lectures = Lecture.objects.filter(member=user)
    return render(request, 'my_page/my_lecture.html', {'lectures': lectures})


#수강신청
@login_required
def join_lecture(request, id):
    user = request.user
    lecture = Lecture.objects.get(pk=id)

    if lecture.member.count() >= lecture.max_member:
        return render(request, 'my_page/max.html')

    else:
        lecture.member.add(user)
        lecture.save()
    return render(request, 'my_page/join_lecture.html')


#수강취소
@login_required
def cancel_lecture(request, id):
    user = request.user
    lecture = Lecture.objects.get(pk=id)
    lecture.member.remove(user)
    return render(request, 'my_page/cancel_lecture.html')


#관심등록강의
def concerned_lecture(request):
    user = request.user
    concerned_lectures = Lecture.objects.filter(lecture_concern=user)

    return render(request, 'my_page/concerned_lecture.html', {'concerned_lectures': concerned_lectures})


#관심등록
@login_required
@require_POST
def lecture_concern(request, id):
    lecture = get_object_or_404(Lecture, pk=id)
    user = request.user
    check_concern = lecture.lecture_concern.filter(id=user.id)

    if check_concern.exists():
        lecture.lecture_concern.remove(user.id)
        lecture.lecture_concern_count -= 1
        lecture.save()
    else:
        lecture.lecture_concern.add(user.id)
        lecture.lecture_concern_count += 1
        lecture.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


#질문
def my_qna(request):
    user = request.user
    my_questions = Question.objects.filter(author_id=user)
    my_answers = Answer.objects.filter(author_id=user)
    my_comments = Comment.objects.filter(author_id=user)
    context = {
        'my_questions': my_questions,
        'my_answers': my_answers,
        'my_comments': my_comments,
    }

    return render(request, 'my_page/my_qna.html', context)



#회원탈퇴
def delete(request):
    if request.method == 'POST':
        form = PasswordCheckForm(request.user, request.POST)
        if form.is_valid():
            request.user.delete()
            logout(request)
            messages.success(request, "회원탈퇴가 완료되었습니다.")
            return redirect('home')
    else:
        messages.error("비밀번호가 틀립니다.")
        form = PasswordCheckForm(request.user)

    return render(request, 'my_page/delete.html', {'form': form})

my_page/templates/my_page/cancel_lecture.html
{% extends 'base.html' %}
{% block main_area %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div style = "padding-left:200px; padding-top:30px;">
    <div class="row">
        <h1>수강취소완료</h1>
        <div class="col-lg-9 mt-0 pl-5">
            <hr class="mb-4">
            <div class="row">
              <div class="row2"><a href="{% url 'my_page:my_page' %}" class="btn btn-outline-success float-right my-4">마이페이지</a>
              <a href="{% url 'my_page:my_lecture' %}" class="btn btn-outline-success float-right my-4">수강강의목록</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

my_page/templates/my_page/concerned_lecture.html
{% extends 'base.html' %}
{% block title %}My Page - Concerned{% endblock %}
{% block main_area %}
{% load static %}

<link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}" media="screen">
<h1>관심강의목록</h1>
<section>
    <div class="row">
        {% for concerned_lecture in concerned_lectures %}
        <div class="row2 ml-2"><a href="{{ concerned_lecture.get_absolute_url }}" class="text-success"><h3>강좌명: {{concerned_lecture.class_name}}</h3></a></div>
        <div class="row2 ml-3">과목: {{concerned_lecture.subject}}</div>
        <div class="row2 ml-3">레벨: {{concerned_lecture.level}}</div>
        <div class="row2 ml-3">수강기간: {{concerned_lecture.period}}</div>
        <div class="row2 ml-3">필요이수과목: {{concerned_lecture.pre_ready}}</div>

        <div class="add-to-wishlist">
            <form action = "{% url 'my_page:lecture_concern' concerned_lecture.id %}" method="post">
                {% csrf_token %}
                <h6><i class="fas fa-heart fa-lg" style="color:#ed4956;"></i>
                    <button type="submit" class="btn btn-link text-dark text-decoration-none">CANCEL WISHLIST</button></h6>
            </form>
        </div>
        <hr class="mb-4">
        {% endfor %}
    </div>
</section>

{% endblock %}

my_page/templates/my_page/delete.html
{% extends 'base.html' %}
{% block main_area %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div style = "padding-left:200px; padding-top:30px;">
    <div class="row">
        <h1 class="text-danger">회원탈퇴</h1>
        <div class="col-lg-9 mt-0 pl-5">
        <hr class="mb-4">
        <div class="row">
        <form method="POST" novalidate>
            {% csrf_token %}
            <h5 class="text-danger">{{ user.username }} 회원님의 계정이 삭제됩니다
            <div>
                <label name="label_password" for="{{ form.password.id_for_label }}">{{ form.password.label }}</label>
                {{ form.password }}
                {% if form.password.errors %}
                <script type="text/javascript">
                    document.getElementsByName('password')[0].setAttribute('class','form-control is-invalid')
                </script>
                    {% for error in form.password.errors %}
                    <div class="invalid-feedback"></div>
                        {{ error }}
                    {% endfor %}
                {% endif %}
            </div>
            </h5>
            <label>
                <input type="checkbox" name="ck" onclick="checkDisable(this.form)">
                <span>확인</span>
            </label>
            <div>
            <a href="#" class="btn btn-outline-danger float-right my-4" data-toggle="modal" data-target="#exampleModal2">탈퇴</a>
                <a href="{% url 'home' %}" class="btn btn-outline-success float-right my-4">메인페이지</a>
                </div>
            <div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel2" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel2">회원탈퇴</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        탈퇴 하시겠습니까?
                    </div>
                    <div class="modal-footer">
                        <button type="submit" name="bt" disabled="true" class="btn btn-success">탈퇴하기</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">취소하기</button>
                    </div>
                </div>
            </div>
            </div>

        </form>
<script type="text/javascript">
    function checkDisable(form) {
        if (form.ck.checked == true) {
            form.bt.disabled = false;
        } else {
            form.bt.disabled = true;
        }
    }
</script>

{% endblock %}

my_page/templates/my_page/join_lecture.html
{% extends 'base_lecture_list.html' %}
{% block main_area %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div style = "padding-left:200px; padding-top:30px;">
    <div class="row">
        <h1>수강신청완료</h1>

        <div class="col-lg-9 mt-0 pl-5">
            <hr class="mb-4">
            <div class="row">
                <div class="row2"><a href="{% url 'lecture:index' %}" class="btn btn-outline-success float-right my-4">강의목록 돌아가기</a>
                    <a href="{% url 'my_page:my_lecture' %}" class="btn btn-outline-success float-right my-4">수강강의목록</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

my_page/templates/my_page/max.html
{% extends 'base.html' %}
{% block main_area %}

모집종료

{% endblock %}

my_page/templates/my_page/my_lecture.html
{% extends 'base.html' %}
{% block title %}My Page - Lecture{% endblock %}
{% block main_area %}
{% load static %}

<link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}" media="screen">
<h1>수강강의목록</h1>
<section class="" id="my_lecture">
    <div class="row">
        {% for lecture in lectures %}
        {% if lecture.lecture_image %}
        <figure class="col-2 my_lecture"><img src="{{ lecture.lecture_image.url}}" class="img-fluid rounded-start" alt="..." width="350px" height="350px"></figure>
        {% endif %}
        <div class="col-4 mt-4">
            <div class="row2 "><a href="{{ lecture.get_absolute_url }}" class="text-success"> <h3>강좌명:  {{lecture.class_name}}</h3></a></div>
            <div class="row2 ">과목: {{lecture.subject}}</div>
            <div class="row2 ">레벨: {{lecture.level}}</div>
            <div class="row2 ">수강기간: {{lecture.period}}</div>
            <div class="row2 ">필요이수과목: {{lecture.pre_ready}}</div>
        </div>
        <div class="row">
            <a href="#" class="btn btn-outline-success float-right my-4 ml-3" data-toggle="modal" data-target="#exampleModal2" style="width:80%; max-width:100px">수강취소</a>
        </div>
        <hr class="mb-4">
        <div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel2" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel2">수강 취소</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        수강취소를 하시겠습니까?
                    </div>
                    <div class="modal-footer">
                        <a href="{% url 'my_page:cancel_lecture' lecture.id %}"><button type="button" class="btn btn-success">취소</button></a>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">뒤로가기</button>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</section>
<a href="{% url 'lecture:index' %}"><button type="button" class="btn btn-outline-success">강의목록보러가기</button></a>

{% endblock %}

my_page/templates/my_page/my_page.html
{% extends 'base.html' %}
{% block title %}My Page{% endblock %}

{% block main_area %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

<div class="row">
    <div class="col-md-3 col-lg-2" id="sidebar-wrapper">
        <div class="shop-widget" id="categories-card">
            <aside class="widget widget-categories">
                <ul class="list-group rounded">
                    <li class="list-group-item bg-light"><h2 class="sidebar-title text-center">
                        빠른메뉴
                    </h2>
                    </li>
                    <li class="list-group-item bg-light"><i class="fa fa-angle-double-right text-success"></i><a href="#my_page" class="smoothscroll text-success">개인정보</a></li>
                    <li class="list-group-item bg-light"><i class="fa fa-angle-double-right text-success"></i><a href="{% url 'my_page:update' %}" class="text-success">정보수정</a></li>
                    <li class="list-group-item bg-light"><i class="fa fa-angle-double-right text-success"></i><a href="#my_lecture" class="smoothscroll text-success">수강강의목록</a></li>
                    <li class="list-group-item bg-light"><i class="fa fa-angle-double-right text-success"></i><a href="{% url 'lecture:index' %}" class="text-success">수강신청</a></li>
                    <li class="list-group-item bg-light"><i class="fa fa-angle-double-right text-success"></i><a href="#my_qna" class="smoothscroll text-success">나의 QnA</a></li>
                </ul>
            </aside>
        </div>
    </div>


    <div class="col-lg-9 mt-0 pl-5">
        <section id="my_page">
            <h3 id="profile">개인정보</h3>
            <hr class="mb-4">

            <div class="row">
                <div class="row"><h5>아이디: {{user.username}}</h5></div>
                <div class="row"><h5>이름: {{user.last_name}}{{user.first_name}}</h5></div>
                <div class="row"><h5>Email: {{user.email}}</h5></div>
            </div>

            <div class="btn-group">
                <a href="{% url 'my_page:update' %}"><button type="button" class="btn btn-outline-success">정보수정</button></a>
                <form action= "{% url 'my_page:delete' %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="회원탈퇴" class="btn btn-outline-danger" style="position:relative; left:5px; ">
                </form>
            </div>

        </section>
        <!-- 강의 목록 -->
        <section id="my_lecture">
            <h3>수강강의목록</h3>
            <hr class="mb-4">
            <div class="row">
                {% for lecture in lectures %}

                <div class="row"><h5>강좌명:  {{lecture.class_name}}</h5></div>

                {% endfor %}
            </div>
            <a href="{% url 'my_page:my_lecture' %}"><button type="button" class="btn btn-outline-success" style="position:absolute left:110px; bottom:150px;">상세보기</button></a>
            <a href="{% url 'lecture:index' %}"><button type="button" class="btn btn-outline-success">수강신청</button></a><br>
        </section>

        <section id="concern_lecture" class="">
            <h3 class="concern_lecture_title">관심강의목록</h3>
            <hr class="mb-4">
            <div class="col-20">
                {% for concerned_lecture in concerned_lectures %}
                <div class="row"><h5>강좌명:  {{concerned_lecture.class_name}}</h5></div>
                {% endfor %}
            </div>
            <div class="row2"><a href="{% url 'my_page:concerned_lecture' %}"><button type="button" class="btn btn-outline-success">상세보기</button></a></div><br>
        </section>

        <section id="my_qna" class="">
            <h3 class="my_qna_title">나의 QnA</h3>
            <hr class="mb-4">
            <div class="col-xs-10">
                <div class="row2"><a href="{% url 'my_page:my_qna' %}"><button type="button" class="btn btn-outline-success">상세보기</button></a></div><br>
            </div>
        </section>
    </div>
</div>

{% endblock %}

my_page/templates/my_page/my_qna.html
{% extends 'base.html' %}
{% block title %}My Page - QnA{% endblock %}
{% block main_area %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<h1>나의 QnA</h1>
<div class="row">
    <section id="my_question">
      <h2 id="question">Question</h2>
      <hr class="mb-4">
      <div class="row">
            {% for my_question in my_questions %}
            <div class="row2 ml-2"><h5><a href="{{ my_question.get_absolute_url }}" class="text-success">{{my_question.subject}} / {{my_question.create_date}}</a></h5></div>
            {% endfor %}<br>
      </div>
    </section>

    <section id="my_answer">
      <h2 id="answer">Answer</h2>
      <hr class="mb-4">
      <div class="row">
            {% for my_answer in my_answers %}
            <div class="row2 ml-2"><h5><a href="{{ my_answer.question.get_absolute_url }}" class="text-success">{{my_answer.content}} / {{my_answer.create_date}}</a></h5></div>
            {% endfor %}
        <br>
      </div>
    </section>

    <section id="my_comment">
      <h2 id="comment">Comment</h2>
      <hr class="mb-4">
        <div class="row">
            {% for my_comment in my_comments %}
            {% if my_comment.question_id != NULL %}
            <div class="row2 ml-2"><h5><a href="{{ my_comment.question.get_absolute_url }}" class="text-success">{{my_comment.content}} / {{my_comment.create_date}}</a></h5></div>
            {% elif my_comment.answer_id != NULL %}
            <div class="row2 ml-2"><h5><a href="{{ my_comment.answer.question.get_absolute_url }}" class="text-success">{{my_comment.content}} / {{my_comment.create_date}}</a></h5></div>
            {% endif %}
            {% endfor %}
        </div><br>

    </section>
</div>

{% endblock %}

my_page/templates/my_page/update.html
{% extends 'base.html' %}
{% block title %}My Page - Profile{% endblock %}
{% block main_area %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div style = "padding-left:200px; padding-top:30px;">
    <div class="row">
        <h1>회원정보수정</h1>
        <div class="col-lg-9 mt-0 pl-5">
            <hr class="mb-4">
            <div class="row">
                <form action = "{% url 'my_page:update'%}" method = "POST">
                    {% csrf_token %}
                    아이디: {{user.username}} <br><br>
                    이름: {{user.last_name}}{{user.first_name}} <br><br>
                    이메일: <input type="email" class="form-control" id="email" name="email" value="{{user.email}}"><br><br>
                    <a href="#" class="btn btn-outline-success float-right my-4" data-toggle="modal" data-target="#exampleModal2">수정</a>
                    <div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel2" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel2">수정</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    정보를 수정하시겠습니까?
                                </div>
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-success">수정</button></a>
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">취소하기</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}