management/urls.py
from django.contrib import admin
from django.urls import path, include
from common.views import HomeView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('lecture/', include('lecture.urls')),
    path('common/', include('common.urls')),
    path('my_page/', include('my_page.urls')),
    path('qna/', include('qna.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qna/urls.py
from django.urls import path
from . import views

app_name = 'qna'

urlpatterns = [
    path('', views.index, name='index'),
    # 127.0.0.1:8000/qna 가 디폴트
    path('<int:question_id>/', views.detail, name='detail'),
    # 127.0.0.1:8000/qna/ + int값이 들어옴 -> question_id
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    # 127.0.0.1:8000/qna/answer/creat/number$$$
    path('question/create/', views.question_create, name='question_create'),
    # 127.0.0.1:8000/qna/question/create/
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    path('comment/create/question/<int:question_id>/', views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', views.comment_delete_answer, name='comment_delete_answer'),
    path('vote/question/<int:question_id>/', views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', views.vote_answer, name='vote_answer'),
]

qna/models.py
from django.db import models
from common.models import CustomUser

class Question(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(CustomUser, related_name='voter_question')  # 추천인 추가

    def get_absolute_url(self):
        return f'/qna/{self.pk}/'

    def __str__(self):
        return self.subject


class Answer(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(CustomUser, related_name='voter_answer')

    def get_absolute_url(self):
        return f'/qna/{self.pk}/'

class Comment(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return f'/qna/{self.pk}/'

qna/forms.py
from django import forms
from .models import Question, Answer, Comment


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        # }
        labels = {
            'subject': '제목',
            'content': '내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }

qna/views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from .models import Question, Answer, Comment
from .forms import QuestionForm, AnswerForm, CommentForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages


# Create your views here.


def index(request):
    """
    Q&A 목록 출력
    """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    # 조회
    question_list = Question.objects.order_by('-create_date')
    # 페이징처리
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}
    return render(request, './qna/question_list.html', context)


def detail(request, question_id):
    """
    Q&A 내용 출력
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, './qna/question_detail.html', context)

@login_required(login_url='common:login')
# 비로그인 시 질문 작성을 하면 오류페이지가 발생하도록 하는게 아닌 로그인을 요구하는 페이지로 이동하게
def answer_create(request, question_id):
    """
    Q&A 답변등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('qna:detail', question_id=question.id), answer.id))
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'qna/question_detail.html', context)
    # render, redirect 개념 정리 answer_create같은 경우 url이 아닌 int:question이라 다르게 연결 (urls.py참조)

@login_required(login_url='common:login')
def question_create(request):
    """
    Q&A 질문등록
    """
    if request.method == 'POST':
        print("=====>",request.user)
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user  # author 속성에 로그인 계정 저장
            question.create_date = timezone.now()
            question.save()
            return redirect('qna:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'qna/question_form.html', context)


@login_required(login_url='common:login')
def question_modify(request, question_id):
    """
    Q&A 질문수정
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('qna:detail', question_id=question.id)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('qna:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'qna/question_form.html', context)


@login_required(login_url='common:login')
def question_delete(request, question_id):
    """
    Q&A 질문삭제
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('qna:detail', question_id=question.id)
    question.delete()
    return redirect('qna:index')


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    """
    Q&A 답변수정
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('qna:detail', question_id=answer.question.id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('qna:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'qna/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    """
    Q&A 답변삭제
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('qna:detail', question_id=answer.question.id)


@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    """
    Q&A 질문댓글등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.question = question
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('qna:detail', question_id=comment.question.id), comment.id))
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'qna/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    """
    Q&A 질문댓글수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('qna:detail', question_id=comment.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('qna:detail', question_id=comment.question.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'qna/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_question(request, comment_id):
    """
    Q&A 질문댓글삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('qna:detail', question_id=comment.question.id)
    else:
        comment.delete()
    return redirect('qna:detail', question_id=comment.question.id)


@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    """
    Q&A 답글댓글등록
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            return redirect('qna:detail', question_id=comment.answer.question.id)
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'qna/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    """
    Q&A 답글댓글수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('qna:detail', question_id=comment.answer.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('qna:detail', question_id=comment.answer.question.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'qna/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    """
    Q&A 답글댓글삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('qna:detail', question_id=comment.answer.question.id)
    else:
        comment.delete()
    return redirect('qna:detail', question_id=comment.answer.question.id)


@login_required(login_url='common:login')
def vote_question(request, question_id):
    """
    Q&A 질문추천등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        question.voter.add(request.user)
    return redirect('qna:detail', question_id=question.id)


@login_required(login_url='common:login')
def vote_answer(request, answer_id):
    """
    Q&A 답글추천등록
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        answer.voter.add(request.user)
    return redirect('qna:detail', question_id=answer.question.id)

qna/templates/qna/answer_form.html
{% extends 'base_community_list.html' %}
{% block title %}Community - form {% endblock %}
{% block main_area %}

<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-outline-success float-right">저장하기</button>
    </form>
</div>

{% endblock %}

qna/templates/qna/comment_form.html
{% extends 'base_community_list.html' %}
{% block title %}Community - form {% endblock %}
{% block main_area %}

<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control"name="content" id="content"
                      rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-outline-success float-right">저장하기</button>
    </form>
</div>

{% endblock %}

qna/templates/qna/question_detail.html
{% extends 'base_community_list.html' %}
{% block title %}Community - {{ question.subject }}{% endblock %}
{% block main_area %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div class="container my-3">
    <!-- 사용자오류 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
        {% endfor %}
    </div>
    {% endif %}
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="row my-3">
        <div class="col-1"> <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{question.voter.count}}</div>
            <a href="{% url 'qna:vote_question' question.id  %}" data-uri="{% url 'qna:vote_question' question.id  %}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11"> <!-- 질문영역 -->
            <!-- 기존내용 -->
            <div class="card">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
                    <div class="d-flex justify-content-end text-dark">
                        {% if question.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3 text-dark">
                            <div class="mb-2">modified at</div>
                            <div>{{ question.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left text-dark">
                            <div class="mb-2 ">{{ question.author.username }}</div>
                            <div>{{ question.create_date }}</div>
                        </div>
                    </div>
                    {% if request.user == question.author %}
                    <div class="my-3">
                        <a href="#" class="btn btn-outline-success float-right my-4" data-toggle="modal" data-target="#exampleModal2">삭제</a>
                        <a href="{% url 'qna:question_modify' question.id  %}"
                           class="btn btn-outline-success float-right my-4" >수정</a>

                        <div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel2" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel2">질문 삭제</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        질문을 삭제하시겠습니까?
                                    </div>
                                    <div class="modal-footer">
                                        <a href="{% url 'qna:question_delete' question.id %}" class="delete btn btn-sm btn-outline"
                                           data-uri="{% url 'qna:question_delete' question.id  %}"><button type="button" class="btn btn-outline-success">삭제</button></a>
                                        <button type="button" class="btn btn-outline-success" data-dismiss="modal">취소</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>

                    <!-- 질문 댓글 Start -->
                    {% if question.comment_set.count > 0 %}
                    <div class="mt-3">
                        {% for comment in question.comment_set.all %}  <!-- 등록한 댓글을 출력 -->
                        <a name="comment_{{ comment.id }}"></a>
                        <div class="comment py-2 text-muted">  <!-- 댓글 각각에 comment 스타일 지정 -->
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                               - {{ comment.author }}, {{ comment.create_date }}
                                {% if comment.modify_date %}
                                (수정:{{ comment.modify_date }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'qna:comment_modify_question' comment.id  %}" class="small text-dark">수정</a>
                            <a href="{% url 'qna:comment_delete_question' comment.id  %}" class="small delete text-dark"
                               data-uri="{% url 'qna:comment_delete_question' comment.id  %}">삭제</a>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{% url 'qna:comment_create_question' question.id  %}"
                           class="small text-dark" ><small>댓글 추가 ..</small></a>  <!-- 댓글 추가 링크 -->
                    </div>
                    <!-- 질문 댓글 End -->
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <a name="answer_{{ answer.id }}"></a>
    <div class="row my-3">
        <div class="col-1">  <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{answer.voter.count}}</div>
            <a href="{% url 'qna:vote_answer' answer.id  %}" data-uri="{% url 'qna:vote_answer' answer.id  %}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11">  <!-- 답변영역 -->
            <!-- 기존내용 -->
            <div class="card">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
                    <div class="d-flex justify-content-end text-dark">
                        {% if answer.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3 text-dark">
                            <div class="mb-2">modified at</div>
                            <div>{{ answer.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left text-dark">
                            <div class="mb-2 ">{{ answer.author.username }}</div>
                            <div>{{ answer.create_date }}</div>
                        </div>
                    </div>
                    {% if request.user == answer.author %}
                    <div class="my-3">
                        <a href="{% url 'qna:answer_delete' answer.id  %}" class="delete btn btn-outline-success float-right my-4 "
                           data-uri="{% url 'qna:answer_delete' answer.id  %}">삭제</a>
                        <a href="{% url 'qna:answer_modify' answer.id  %}"
                           class="btn btn-outline-success float-right my-4">수정</a>
                    </div>
                    {% endif %}
                    {% if answer.comment_set.count > 0 %}
                    <div class="mt-3">
                        {% for comment in answer.comment_set.all %}
                        <a name="comment_{{ comment.id }}"></a>
                        <div class="comment py-2 text-muted text-dark">
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                        - {{ comment.author }}, {{ comment.create_date }}
                        {% if comment.modify_date %}
                        (수정:{{ comment.modify_date }})
                        {% endif %}
                    </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'qna:comment_modify_answer' comment.id  %}" class="small text-dark">수정</a>
                            <a href="{% url 'qna:comment_delete_answer' comment.id  %}" class="small delete text-dark"
                               data-uri="{% url 'qna:comment_delete_answer' comment.id  %}">삭제</a>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{% url 'qna:comment_create_answer' answer.id  %}"
                           class="small text-dark"><small>댓글 추가 ..</small></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'qna:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="form-group">
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
                      name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변 등록" class="btn btn-outline-success float-right">
    </form>
</div>

{% endblock %}

qna/templates/qna/question_form.html
{% extends 'base_community_list.html' %}
{% block title %}Community - form {% endblock %}
{% block main_area %}

<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3" >
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-outline-success float-right">저장하기</button>
    </form>
</div>

{% endblock %}

qna/templates/qna/question_list.html
{% extends 'base_community_list.html' %}
{% load qna_filter %}
{% block title %}Community{% endblock %}
{% block main_area %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<table class="table">
    <thead>
    <tr class="text-center thead-dark">
        <th>번호</th>
        <th>추천</th>
        <th style="width:50%">제목</th>
        <th>글쓴이</th>
        <th>작성일시</th>
    </tr>
    </thead>
    <tbody>
    {% if question_list %}
    {% for question in question_list %}
    <tr class="text-center">
        <td>
            <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
            {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
        </td>
        <td>
            {% if question.voter.all.count > 0 %}
            <span class="badge badge-warning px-2 py-1">{{ question.voter.all.count }}</span>
            {% endif %}
        </td>
        <td class="text-center">
            <a href="{% url 'qna:detail' question.id %}" class="text-dark">{{ question.subject }}</a>
            {% if question.answer_set.count > 0 %}
            <span class="text-danger small ml-2">{{ question.answer_set.count }}</span>
            {% endif %}
        </td>
        <td>{{ question.author.username }}</td>  <!-- 글쓴이 추가 -->
        <td>{{ question.create_date }}</td>
    </tr>
    {% endfor %}
    {% else %}
    <tr>
        <td colspan="3">질문이 없습니다.</td>
    </tr>
    {% endif %}
    </tbody>
</table>
<!-- 페이징처리 시작 -->
<ul class="pagination justify-content-center">
    {% if question_list.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ question_list.previous_page_number }}" style="background-color:white; color:black;">이전</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#" style="background-color:white; color:black;">이전</a>
    </li>
    {% endif %}
    {% for page_number in question_list.paginator.page_range %}
    {% if page_number == question_list.number %}
    <li class="page-item active" aria-current="page">
        <a class="page-link" href="?page={{ page_number }}"style="background-color:#088681; color:white;">{{ page_number }}</a>
    </li>
    {% else %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_number }}"style="background-color:white; color:black;">{{ page_number }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if question_list.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ question_list.next_page_number }}" style="background-color:white; color:black;">다음</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#" style="background-color:white; color:black;">다음</a>
    </li>
    {% endif %}
</ul>
<!-- 페이징처리 끝 -->
<a href="{% url 'qna:question_create' %}" class="btn btn-outline-success float-right">질문 등록</a>

{% endblock %}