common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'common'

urlpatterns = [
    #path('', views.main, name='main'),
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('find_id/', views.find_id, name='find_id'),
    path('find_pw/', views.find_pw, name='find_pw'),
    path('find_pw/reset_pw/<int:pk>', views.reset_pw, name='reset_pw'),
    path('find_pw/verify/<int:pk>', views.verify, name='verify'),
    path('lecture/searching/', views.searched_lecture, name='searched_lecture'),
    path('message/', views.customer_message, name='customer_message'),
    path('subscribe/', views.subscribe, name='subscribe'),
]

management/urls.py
from django.contrib import admin
from django.urls import path, include
from common.views import HomeView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('lecture/', include('lecture.urls')),
    path('common/', include('common.urls')),
    path('my_page/', include('my_page.urls')),
    path('qna/', include('qna.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_page/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'my_page'
urlpatterns = [
    path('', views.my_page, name='my_page'),
    path('update/', views.update, name='update'),
    path('my_lecture/', views.my_lecture, name='my_lecture'),
    path('delete/', views.delete, name='delete'),
    path('join_lecture/<int:id>', views.join_lecture, name='join_lecture'),
    path('cancel_lecture/<int:id>', views.cancel_lecture, name='cancel_lecture'),
    path('lecture_concern/<int:id>', views.lecture_concern, name='lecture_concern'),
    path('concerned_lecture/', views.concerned_lecture, name='concerned_lecture'),
    path('my_qna/', views.my_qna, name='my_qna'),
    # path('answer_url/<int:answer_id>', views.answer_url, name='answer_id'),
]

qna/urls.py
from django.urls import path
from . import views

app_name = 'qna'

urlpatterns = [
    path('', views.index, name='index'),
    # 127.0.0.1:8000/qna 가 디폴트
    path('<int:question_id>/', views.detail, name='detail'),
    # 127.0.0.1:8000/qna/ + int값이 들어옴 -> question_id
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    # 127.0.0.1:8000/qna/answer/creat/number$$$
    path('question/create/', views.question_create, name='question_create'),
    # 127.0.0.1:8000/qna/question/create/
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    path('comment/create/question/<int:question_id>/', views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', views.comment_delete_answer, name='comment_delete_answer'),
    path('vote/question/<int:question_id>/', views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', views.vote_answer, name='vote_answer'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}" media="screen">
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'images/unedulogo.png' %}" rel="icon">
    <link href="{% static 'images/unedulogo.png' %}" rel="unedulogo">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
     a {
     text-decoration:none !important
     }
     #main_area{
        padding-top:87px;

     }
     ul{
       list-style:none;
       }
    </style>
</head>
<body>
{% include 'navbar.html' %}
<main id="main_area" class="bg-white">
    <div class="breadcrumbs-area">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumbs">
                    <img src="{% static 'images/banner1.png' %}" width="100%" height="auto">
                </div>
            </div>
        </div>
    </div>
    <div id="main_container" class="container bg-white">
        <section>
            {% block main_area %}
            {% endblock %}
        </section>
    </div>
</main>

{% include 'footer.html' %}
<script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/a076d05399.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

<!-- Template Main JS File -->
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/base_community_list.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}" media="screen">
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'images/unedulogo.png' %}" rel="icon">
    <link href="{% static 'images/unedulogo.png' %}" rel="unedulogo">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
     a {
     text-decoration:none !important
     }
     #main_area{
        padding-top:87px;

     }
     ul{
       list-style:none;
       }
    </style>
</head>
<body>
{% include 'navbar.html' %}
<main id="main_area" class="bg-white">
    <div class="breadcrumbs-area">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumbs">
                    <img src="{% static 'images/banner3.png' %}" width="100%" height="auto">
                </div>
            </div>
        </div>
    </div>
    <div id="main_container" class="container bg-white">
        <section>
            {% block main_area %}
            {% endblock %}
        </section>
    </div>
</main>

{% include 'footer.html' %}
<script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/a076d05399.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

<!-- Template Main JS File -->
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/base_lecture_list.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}" media="screen">
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'images/unedulogo.png' %}" rel="icon">
    <link href="{% static 'images/unedulogo.png' %}" rel="unedulogo">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
     a {
     text-decoration:none !important
     }
     #main_area{
        padding-top:87px;

     }
     ul{
       list-style:none;
       }
    </style>
</head>
<body>
{% include 'navbar.html' %}
<main id="main_area" class="bg-white">
    <div class="breadcrumbs-area">
        <div class="row">
            <div class="col-md-12">
                <div class="breadcrumbs">
                    <img src="{% static 'images/bannermain.png' %}" width="100%" height="auto">
                </div>
            </div>
        </div>
    </div>
    <div id="main_container" class="container bg-white">
        <section>
            {% block main_area %}
            {% endblock %}
        </section>
    </div>
</main>

{% include 'footer.html' %}
<script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/a076d05399.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

<!-- Template Main JS File -->
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/footer.html
{% load static %}

<!-- ======= Footer ======= -->
<footer id="footer">
    <div class="footer-top">
        <div class="container">
            <div class="row">

                <div class="col-lg-4 col-md-6">
                    <div class="footer-info">
                        <h3>UneducatedSystem</h3>
                        <p class="pb-3"><em>For those who want to receive new software training information every day, or for business partnership or advertising inquiries, please contact below.</em></p>
                        <p>
                             508, Eonju-ro, Gangnam-gu, Seoul, Republic of Korea<br>
                            <br><br>
                            <strong>Phone:</strong> +82 2-1544-9001<br>
                            <strong>Email:</strong> vkbk62@gmail.com<br>
                        </p>
                        <div class="social-links mt-3">
                            <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                            <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                            <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                            <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                            <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                        </div>
                    </div>
                </div>

                <div class="col-lg-2 col-md-6 footer-links">
                    <h4>Useful Links</h4>
                    <ul>
                        <li><i class="bx bx-chevron-right"></i> <a href="/">Home</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="/#contact">Contact us</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="/#services">Services</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="/#team">Meet our Team</a></li>
                    </ul>
                </div>

                <div class="col-lg-2 col-md-6 footer-links">
                    <h4>Our Services</h4>
                    <ul>
                        <li><i class="bx bx-chevron-right"></i> <a href="/common/lecture/searching/?searching=software">Software</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="/common/lecture/searching/?searching=web">Web</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="/common/lecture/searching/?searching=product%20management">Product Management</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="/common/lecture/searching/?searching=security">Security</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="/common/lecture/searching/?searching=marketing">Marketing</a></li>
                    </ul>
                </div>

                <div class="col-lg-4 col-md-6 footer-newsletter">
                    <h4>Our Newsletter</h4>
                    <p>Get free technical information from IT professionals every week.</p>

                    <form id="subscribeForm" action="{% url 'common:subscribe' %}" method="post">
                        {% csrf_token %}
                        <input type="email" name="email"><input type="submit" value="Subscribe">
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong><span>UneducatedSystem</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/squadfree-free-bootstrap-template-creative/ -->
            Designed by <a href="https://bootstrapmade.com/">UneducatedSystem</a>
        </div>
    </div>

    <script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
</footer><!-- End Footer -->

templates/form_errors.html
<!DOCTYPE html>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
{% load static %}

<header id="header" class="fixed-top">
    <div class="container d-flex align-items-center justify-content-between">
        <div class="logo">
            <h1 class="text-light"><a style="font-size:28px; font-weight:bold;" href="/"><span>UneducatedSystem</span></a></h1>
        </div>
        <nav id="navbar" class="navbar">
            <ul>
                <a class="nav-link " href="/lecture/">Services</a>
                <a class="nav-link scrollto" href="/qna/">Community</a>
                {% if user.is_authenticated %}
                <a class="nav-link scrollto" href="{% url 'common:logout' %}">Log Out</a>
                <a class="nav-link scrollto" href="{% url 'my_page:my_page' %}">My Page</a>
                {% else %}
                <a class="nav-link scrollto" href="{% url 'common:login' %}">Sign In</a>
                <a class="nav-link scrollto" href="{% url 'common:signup' %}">Sign Up</a>
                {% endif %}
            </ul>
        </nav>
    </div>
</header>